### ISSUE TITLE
Automated detector tilt calibration based on powder standard

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#119]
## Description

This describes some number of functions that should be added to the calibration module, targeted for use at XPD. There are two key cases: images with a full picture of the rings and partial images showing one half or one quadrant.
1. Find the rings
2. Label the rings (n=1, 2, 3) where 0 is the beam.
3. Pass this information to [hexrd](https://github.com/praxes/hexrd). Note the the praxes branch in the most up-to-date as of this writing. Also check out Joel's branch. Tom and Eric are in touch with Joel -- good idea to touch base.
## Requirements

Tests should include full rings and partial rings with tilts up to 1 degree. A stretch would be supporting experiments that tilt the detector 45 degree, but this is not needed for XPD at this time.
## Useful Equations
1. two_theta = atan((pixel_size \* 1000 \* dist_from_center) / dist_from_sample) -- implemented as `core.radius_to_twotheta`
2. q = 4 \* pi \* sin(two_theta / 2) / wavelength -- implemented as `core.twotheta_to_q`
## Tasks
- [x] find pixel center at pixel resolution -- implemented as `image.find_ring_center_acorr_1D` but this only works on images showing the full rings, and it is slow
- [x] Refine center to subpixel resolution -- implemented as `calibration.refine_center`, which also assumed full rings
- [x] integrate based on pixel res center -- implemented as `core.bin_1D`, but `x` and `y` really mean `r` and `intensity` in this context, which results in a plot of peaks I(r)
- [x] fit and find peaks in I and label them beginning with 1 -- implemented as `calibration.estimate_d_blind`, which should be fixed to be less blind. Also, its main result (distance to detector which we should not be calling "d") is actually found by hexrd, so we only want the peak-labeling bit, which we will improve anyway.
- [ ] verify peak labeling (something like q_1 / q_N should be a constant, but this might depend on detector curvature), looking for gaps or false positives, knowing that the peaks are within some error neighborhood of known locations but at an unknown overall scaling
- [ ] Give hexrd locations of bright pixels with associated ring labels. It returns:
  - distance to detector, 
  - q_0 which the beam center and not necessarily the center of your rings, 
  -  pitch and yaw of the detector, parameterized in some way so pay attention
## Suggestions for improving current implementation
- Use scikit-image region labeling to get rings well enough to guess the center, and from there obtain a radius for each ring.
## One more time through that logic, ignoring implementation
1. Guess center.
2. Find rings.
3. Compare observed ring pattern to known ring pattern (remember scale is unknown) to guess detector distance (i.e. scale). Use n=1 to start.
4. Now look for missing peaks. Is it bad? Try a new detector distance. And so on.
5. Based on that guess, label the rings.
6. Hand off to hexrd.

**Comment by danielballan** [comment]
Note to self: There are tests that generate sample images one can use.

**Comment by danielballan** [comment]
It would be interesting to compare our results to results from the closed-source [FIT2D](http://www.esrf.eu/computing/scientific/FIT2D/). Maybe the hexrd devs have already done this, but we want to make sure our pre-processing code + hexrd give good correspondence.

**Comment by tacaswell** [comment]
@sameera2004 Has been working on these comparisons for the current code vs fit2d

**Comment by danielballan** [comment]
Also, there is [pyFAI](https://github.com/kif/pyFAI), but this splits pixels (i.e., antialiasing) which complicates error propagation as explained in arXiv:1309.3614. The authors of that paper have a Python code for 2D diffraction image integration using a non-splitting algorithm: 

https://github.com/diffpy/diffpy.srxplanar

@tacaswell @sameera2004 Were you aware of this? Have you touched base with the author?

**Comment by danielballan** [comment]
@tacaswell For center detection, did you try http://scikit-image.org/docs/dev/auto_examples/plot_circular_elliptical_hough_transform.html#ellipse-detection?

**Comment by tacaswell** [comment]
I don't remember.  I think so, the auto correlation was the first thing I thought of, was quick enough to write, and it worked well enough on the sample data I had.

I start to get worried about hough-transforms when you have too many free parameters as the size of the voting structure goes as nbins ** n_parameters so for ellipses where you have 5  and if you want to let both the center position and radius range over the whole image with pixel-level accuracy you end up with 2k^4 * number of angles.

**Comment by danielballan** [comment]
Basic geometry reminder:
![](http://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Conic_Sections.svg/500px-Conic_Sections.svg.png)

**Comment by sameera2004** [comment]
About https://github.com/diffpy/diffpy.srxplanar

We used SrXplanner, but to use it we need a calibration details either using fit2d or pyFai. I compared Nikea integration results with fit2d, SrXplanner and next one is changing the fit2d tilt to zero. Attached please find some of the results I got.

![ni_cal_d208mm_300k-0087](https://cloud.githubusercontent.com/assets/5701652/5669251/4b9e6558-9744-11e4-84c6-c8e407919ead.png)
![ni_cal_d208_tail](https://cloud.githubusercontent.com/assets/5701652/5669256/50d12bdc-9744-11e4-9f1a-c0bcd16c3892.png)

![si_std_d204-00002](https://cloud.githubusercontent.com/assets/5701652/5669301/ad15e450-9744-11e4-8d28-93a4e9407155.png)
![si_std_d204-00002_tail](https://cloud.githubusercontent.com/assets/5701652/5669317/b2701b96-9744-11e4-8f7b-b63d7d859cda.png)

![ni-330mm-00006_new](https://cloud.githubusercontent.com/assets/5701652/5669354/e7c1d55a-9744-11e4-9c53-0e6038617871.png)
![ni_cal_d208mm_tail](https://cloud.githubusercontent.com/assets/5701652/5669358/ecea4d46-9744-11e4-925f-c4ce989f92a6.png)

**Comment by sameera2004** [comment]
I think the problem with the Nikea integration (tail) can be fixed with the tilt.

**Comment by tacaswell** [comment]
https://github.com/tacaswell/scikit-xray/tree/calib_tilt <- code for computing slicing into parallel beams The problem here is that it assumes q0 is always the geometric mean of the rings, where as q0 moves one way or the other, relative to the rings, due to the tilt.  Basically in the conversion between the tilted and un-tilted frames there needs to be an extra ` + nasty_trig` term.  It might work, but is probably another 5-10 pages of algebra to make sure the equations are right.

https://github.com/tacaswell/leidenfrost/blob/master/leidenfrost/ellipse.py <- different way to paramterize ellipses.  This has code that fits the general quadratic equation so it should be able to fit any of the conic sections, but the code to convert those values back to things that are easy to understand probably only works for circles/ellipses right now.

**Comment by licode** [comment]
What is the difference between fit2d and fit2d-changed? It looks like Nikea gives low resolution, i.e. Si_STD?

**Comment by tacaswell** [comment]
What does it look like if you use `step` instead of `plot`?  that would
make it clear what the relative bin sizes are.

**Comment by sameera2004** [comment]
# Comparing Calibration Data from ft2d and Nikea

Tif File | Wavelength | X(pixels) difference | Y (pixels) difference | Sample to det distance difference (mm)
 ---------|-----------------|----------------------------|----------------------------|-----------------------------------------------------                                 
Ni-330mm-00006.tif |0.108010 |-0.489764839 |-0.54733646 |0.008858008
Ni_cal2_d208mm_300K-00090.tif |0.1839|-0.47502526 |-0.50448461|0.049152312
Ni_cal3_d208mm_300K-00091.tif | 0.1839 |-0.53402526 |-0.48748461	|0.071571612
Ni_cal_d208mm_300K-00087.tif|	0.1839	|-0.54186985|	-0.56697413|	0.068345563
Ni_NIST_STD_300K_d224-00002.tif|	0.18597|	-0.48196618|	-0.56928314|	0.035765465
Ni_STD_300K_1s_60f-00000.tif|	0.1839|	-0.50867774|	-0.4695646|	0.045455306
Ni_Std_cryo_300K_d650-00052.tif	|0.1839|	-0.49123502	|-0.42877381	|0.06199877
Ni_STD_d204_300K-00003.tif|	0.18597|	-0.49104279|	-0.60712529|	0.020366362
Ni_STD_d204_300K-00004.tif|	0.18597|	-0.40733221|	-0.48005056|	2.6698226079999
Ni_STD_d208mm_300K-00000.tif|	0.1839|	-0.53817995|	-0.49160062|	2.426937471
CeO2-330mm-00005|	-0.616236|	-0.61578|	0.238549
LaB6-330mm-00004|	-0.354164|	-0.05455|	0.058907
Si_STD_d204-00002|	-0.31749|	-0.51384|	0.00861
LaB6_d500_0p72959_2Kx2K_pix200_2| 	-0.24358|	-1.00253|	0.241279

**Comment by sameera2004** [comment]
@licode What is the difference between fit2d and fit2d-changed? 
* fit2d - is the results got from fit2d
* fit2d-changed  - is changing the fit2d calibration file  (tilt zero).  I tried to give the same calibration data I got from Nikea/calibration for fit2d but it didn't work. Only changed the tilt to zero.

**Comment by danielballan** [comment]
We will implement several ways of finding the center and labeling the rings. They will be drop-in replacements for each other. Let the best function win!

Braindump:
* Polar transform
* Machine learning algorithm that knows how to find circles or ellipses out of the box
* Elliptical hough transform (may not be promising though -- see above)

**Comment by CJ-Wright** [comment]
@sameera2004 In the above plots how did you perform the averaging?  Did you use the mean, median, etc?  That could change the integrated values, especially if you have dead pixels or other detector aberrations.  Also is there a way to determine the resolution of the detector in Q space?  I would guess that the resolution would be low at low Q and high at high Q.

Also I have some code in the kitchen sink which is a more function based version of SrXplaner.

How did the graphs compare to pyFAI?

**Comment by sameera2004** [comment]
@CJ-Wright, my code you can see in the radial integration: powder data #236. I used skxray/core/bin_1D for that. Actually I didn't use a mask for fit2d and SrXplanner. I used GSAS in two theta space which also agree with ours but it also have issues in the tail section.  Why do you think the resolution would be low at low Q and high at high Q? 
I will take a look at your code in the kitchen sink.

**Comment by danielballan** [comment]
@CJ-Wright Hi there, I am a new member of the team as of last week. I look forward to collaborating with you here.

One way of illustrating the resolution of the detector in Q space is to use a "stepped" plot line instead of smoothly connected one. See, for example, [this notebook](http://nbviewer.ipython.org/github/danielballan/scikit-xray-examples/blob/tilt-notebook/notebooks/Detector%20Tilt%20Calibration%20Using%20Powder%20Standard.ipynb), which is part of work-in-progress PR at Nikea/scikit-xray-examples#13. If you zoom in on the final plot, the varying resolution in Q is visible. Part of the job of that notebook will be explaining our methodology. Of course the details are in the code, too, but we will make sure to address these questions more accessibly in the notebook.

**Comment by CJ-Wright** [comment]
@sameera2004 I though that there would be higher resolution at high Q (ignoring the issue of the square detector corners) because as the angle increases the difference between the pixel edges decreases.  

Example, consider a detector which has three pixels each with a height of x.  The main beam comes in at the bottom of the lowest pixel.  Thus, the range of two theta which hits the lowest pixel is tan<sup>-1</sup>(x/y) where y is the sample to detector distance, we'll call this th1.  th2 which is the range of two theta which hits the middle pixel is th2 = tan<sup>-1</sup>(2x/y) - th1, likewise th3 = tan<sup>-1</sup>(3x/y) - th1 - th2.  Despite the tan<sup>-1</sup> going up as we move up the detector it does not go up as much as the previous pixel.  Thus, a smaller and smaller range of two theta values fall on the pixels as we go up the detector.

**Comment by CJ-Wright** [comment]
@danielballan It's nice to meet you!  I guess what I am most interested in is a description of the error in our knowledge of the Q in a given pixel.

**Comment by danielballan** [comment]
We should probably include built-in error analysis. From a software
perspective, we might might need to address the fact that the core Python
libraries don't have an established way for returning uncertainties with
data. In the short, anyway, I'll make sure there is some discussion on this
point in the notebook.
