### ISSUE TITLE
TODO before tagging the next release

### ISSUE THREAD

**Issue by ericdill** [scikit-beam/scikit-beam#315]
# skxray.io
- [ ] Move `gsas_writer` function from `save_powder_output.py` into `gsas_reader.py`
- [ ] update the gsas test io functions
- [ ] rename `gsas_reader.py` to `gsas`
- [ ] rename `save_powder_output.py` to `powder.py`
- [ ] rename `save_powder_output.save_output` to `powder.save`
- [ ] rename `avizo_io.py` to `avizo.py`
- [ ] rename `net_cdf_io.py` to `netcdf.py`
- [ ] rename `net_cdf_io.load_netCDF` to `load`

More to come, but in this vein...

**Comment by sameera2004** [comment]
# skxray.core.correlation
- [ ] two time correlation function
